[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DMQTT_MAX_PACKET_SIZE=512

lib_deps =
  bblanchon/ArduinoJson@^7.0.0
  adafruit/Adafruit SSD1306@^2.5.0
  adafruit/Adafruit GFX Library@^1.11.0
  adafruit/Adafruit PN532@^1.3.1
  ricmoo/QRCode@^0.0.1
  knolleary/PubSubClient@^2.8
